### ISSUE TITLE
Protein in explicit water solvent box simulation with Jax_amber

### ISSUE THREAD

**Issue by Byun-jinyoung** [swillow/jax_amber#1]
Is is possible to run MD simulation a large protein (AA>300) in explicit water solvent with Jax_amber?

**Comment by swillow** [comment]
Thank you for expressing your interest. Indeed, it is possible to add the requested feature, and I will make sure to incorporate it soon. However, if your sole purpose is to run molecular dynamics (MD) simulations, I would recommend utilizing OpenMM or other advanced software packages.  It is worth mentioning that I developed "jax_amber" primarily for a project centered around deep machine learning.

**Comment by Byun-jinyoung** [comment]
Thank you for you reply!
I'd like to simulation protein in explicit solvent with MD + deep learning approach (e.g. roughly such as OpenMM + openmm-pytorch although I've never used openmm-pytorch...).
Thus my first idea is combination (JAX_MD in explicit solvent + **'JAX NN potential deep learning'**) for sampling rare event or exploring conformational space more efficiently because JAX support autodifferential.
What do you make of it?

**Comment by swillow** [comment]
Please check the directory 'periodic_system'.
